services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api-clean-node
    ports:
      - '5050:5050'
      - '9222:9222'
    environment:
      PORT: 5050
      MONGO_URL: mongodb://mongo:27017/clean-node-api
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json

  mongo:
    image: mongo:7
    container_name: api-clean-node-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: always

volumes:
  mongo_data:
